(defun dfs (graph sindex visitStatus)
  (if (= (aref visitStatus (- sindex 1)) 0)
    (progn
      (terpri)
      (format t "~D " sindex)
      (setf (aref visitStatus (- sindex 1)) 1)
      (dotimes (i (car (array-dimensions (aref graph (- sindex 1)))))
        (dfs graph (aref (aref graph (- sindex 1)) i) visitStatus)
      )
    )
  )
)

(format t "Enter N The total number of nodes in Graph")
(terpri)
(setf n (read))
(setf graph (make-array n))
(setf visitStatus (make-array n))
(dotimes (k n)
  (setf (aref visitStatus k) 0)
)
(write visitStatus)
(format t "Enter The Adjancency Matrix")
(terpri)
(dotimes (i n)
    (progn
      (loop
          (format t "Enter The number of nodes connected to ~Dth node in graph" (+ i 1))
          (terpri)
          (setf n1 (read))
          (if (> n1 n)
            (progn
              (format t "Enter A Valid number of nodes connected")
              (terpri)
            )
            (return)
          )
      )

      (setf (aref graph i) (make-array n1))
      (dotimes (j n1)
        (loop
            (format t "Enter ~Dth Number Node ~Dth node is connected to" (+ j 1) (+ i 1))
            (terpri)
            (setf (aref (aref graph i) j) (read) )
            (if (> (aref (aref graph i) j) n)
              (progn
                (format t "Enter A Valid node number")
                (terpri)
              )
              (return)
            )
        )
      )
    )
)

(write graph)
(terpri)
(format t "Enter the starting node for DFS traversal 1 --> ~D" n)
(terpri)
(setf startnode (read))
(format t "The DFS traversal of given Graph is")
(terpri)
(dfs graph startnode visitStatus)
